
package com.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderProcessService", targetNamespace = "http://www.ben.com/orderprocess")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcessService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ws.client.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response processOrder(
        @WebParam(name = "arg0", partName = "arg0")
        OrderBean arg0);

}
